### ISSUE TITLE
Unexpected token < in JSON at position 4

### ISSUE THREAD

**Issue by robots4life** [Sirneij/django_svelte_jwt_auth#1]
When a user is logged in `https://django-sveltekit-jwt-auth.vercel.app/accounts/user/abc-uuid` and you hit F5 / refresh in the browser on the User page the message `Unexpected token < in JSON at position 4` is displayed.

Similar to when being on `https://django-sveltekit-jwt-auth.vercel.app/` **with a logged in User**. When you hit F5 there for quite some time the components are displayed with **the state of no user present** and only after some time they change to state of the logged in user. Why is that ?

Also when a user is not logged in and you go to `https://django-sveltekit-jwt-auth.vercel.app/accounts/user/some-random-user` the error 500, `SyntaxError: Unexpected token < in JSON at position 4` is being shown.

Now I do understand that hitting F5 /refresh is not often the case, however specifically with SSR SvelteKit I am kind of wanting to achieve that when the user is logged **no components are shown that have the "no user" state**.

Hope we get a discussion going, I am re-building your tutorial and will try to address this issue.

**Comment by Sirneij** [comment]
Awesome discovery. Just checked it out. Are you with any solution yet? I'm kinda interested in it.

**Comment by robots4life** [comment]
No, for that I have to build backend, what I suspect is that somehow on a `/profile` or `/login` route you don't return JSON data, could that be ?
